"""Fine-tune DistilBERT on router synthetic data and export to ONNX INT8.

Pipeline:
  1. Load data/router_train.jsonl (generated by generate-synth-data.py)
  2. Fine-tune distilbert-base-uncased with HuggingFace Trainer (or TRL SFTTrainer)
  3. Export to ONNX FP32 via transformers.onnx
  4. Quantize ONNX to INT8 via onnxruntime.quantization
  5. Validate: run 10 samples through the INT8 model, assert <10ms/sample on CPU

Requirements (install in mlenv or add to pyproject.toml):
    transformers>=4.40,<5.0
    datasets>=2.20,<3.0
    onnx>=1.16,<2.0
    onnxruntime>=1.18,<2.0

Usage:
    conda activate mlenv
    uv run python scripts/generate-synth-data.py --samples 200
    uv run python scripts/train-router.py
    uv run python scripts/train-router.py --data data/router_train.jsonl \\
        --output data/models/router.onnx --epochs 5 --batch-size 16
"""

from __future__ import annotations

import argparse
import logging
import time
from pathlib import Path

import numpy as np

logger = logging.getLogger(__name__)

_LABEL_NAMES = ["spiritual", "career", "intelligence", "creative"]
_MODEL_NAME = "distilbert-base-uncased"
_MAX_LENGTH = 128


# ── Data loading ──────────────────────────────────────────────────────────────


def load_jsonl(path: Path) -> list[dict]:
    import json

    rows = []
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                rows.append(json.loads(line))
    return rows


def split_train_val(rows: list[dict], val_frac: float = 0.1, seed: int = 42) -> tuple[list, list]:
    import random

    rng = random.Random(seed)  # noqa: S311 — seeded shuffle for ML split, not crypto
    shuffled = rows.copy()
    rng.shuffle(shuffled)
    split = int(len(shuffled) * (1 - val_frac))
    return shuffled[:split], shuffled[split:]


# ── Training ──────────────────────────────────────────────────────────────────


def train(
    data_path: Path,
    output_dir: Path,
    epochs: int = 3,
    batch_size: int = 16,
    lr: float = 2e-5,
    seed: int = 42,
) -> Path:
    """Fine-tune DistilBERT for 4-class intent classification.

    Returns the path to the saved HuggingFace model directory.
    """
    import evaluate
    from datasets import Dataset
    from transformers import (
        AutoModelForSequenceClassification,
        AutoTokenizer,
        DataCollatorWithPadding,
        Trainer,
        TrainingArguments,
    )

    logger.info("Loading training data from %s", data_path)
    rows = load_jsonl(data_path)
    train_rows, val_rows = split_train_val(rows, seed=seed)
    logger.info("Train: %d  Val: %d", len(train_rows), len(val_rows))

    tokenizer = AutoTokenizer.from_pretrained(_MODEL_NAME)

    def tokenize(batch: dict) -> dict:
        return tokenizer(
            batch["text"],
            truncation=True,
            max_length=_MAX_LENGTH,
            padding=False,  # DataCollatorWithPadding handles this
        )

    train_ds = Dataset.from_list([{"text": r["text"], "label": r["label"]} for r in train_rows])
    val_ds = Dataset.from_list([{"text": r["text"], "label": r["label"]} for r in val_rows])

    train_ds = train_ds.map(tokenize, batched=True, remove_columns=["text"])
    val_ds = val_ds.map(tokenize, batched=True, remove_columns=["text"])

    collator = DataCollatorWithPadding(tokenizer=tokenizer)

    model = AutoModelForSequenceClassification.from_pretrained(
        _MODEL_NAME,
        num_labels=len(_LABEL_NAMES),
        id2label={i: n for i, n in enumerate(_LABEL_NAMES)},
        label2id={n: i for i, n in enumerate(_LABEL_NAMES)},
    )

    accuracy_metric = evaluate.load("accuracy")

    def compute_metrics(eval_pred: tuple) -> dict:
        logits, labels = eval_pred
        preds = np.argmax(logits, axis=-1)
        return accuracy_metric.compute(predictions=preds, references=labels)

    hf_output = output_dir / "hf_model"
    hf_output.mkdir(parents=True, exist_ok=True)

    training_args = TrainingArguments(
        output_dir=str(hf_output),
        num_train_epochs=epochs,
        per_device_train_batch_size=batch_size,
        per_device_eval_batch_size=batch_size,
        learning_rate=lr,
        eval_strategy="epoch",
        save_strategy="epoch",
        load_best_model_at_end=True,
        metric_for_best_model="accuracy",
        seed=seed,
        logging_steps=20,
        report_to="none",  # disable wandb / other integrations
        fp16=False,  # CPU training
    )

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_ds,
        eval_dataset=val_ds,
        data_collator=collator,
        compute_metrics=compute_metrics,
    )

    logger.info("Starting fine-tuning (%d epochs, batch=%d, lr=%.0e)", epochs, batch_size, lr)
    trainer.train()

    eval_results = trainer.evaluate()
    logger.info("Final eval: accuracy=%.3f", eval_results.get("eval_accuracy", 0))

    # Save best model + tokenizer
    trainer.save_model(str(hf_output))
    tokenizer.save_pretrained(str(hf_output))
    logger.info("HuggingFace model saved to %s", hf_output)
    return hf_output


# ── ONNX export ───────────────────────────────────────────────────────────────


def export_onnx(hf_model_dir: Path, onnx_fp32_path: Path) -> None:
    """Export HuggingFace model to ONNX FP32."""
    import torch
    from transformers import AutoModelForSequenceClassification, AutoTokenizer

    logger.info("Exporting to ONNX FP32: %s", onnx_fp32_path)
    onnx_fp32_path.parent.mkdir(parents=True, exist_ok=True)

    tokenizer = AutoTokenizer.from_pretrained(str(hf_model_dir))
    model = AutoModelForSequenceClassification.from_pretrained(str(hf_model_dir))
    model.eval()

    dummy_inputs = tokenizer(
        "sample text for export",
        return_tensors="pt",
        max_length=_MAX_LENGTH,
        padding="max_length",
        truncation=True,
    )

    with torch.no_grad():
        torch.onnx.export(
            model,
            args=(dummy_inputs["input_ids"], dummy_inputs["attention_mask"]),
            f=str(onnx_fp32_path),
            input_names=["input_ids", "attention_mask"],
            output_names=["logits"],
            dynamic_axes={
                "input_ids": {0: "batch", 1: "sequence"},
                "attention_mask": {0: "batch", 1: "sequence"},
                "logits": {0: "batch"},
            },
            opset_version=14,
        )
    logger.info("ONNX FP32 export complete: %s", onnx_fp32_path)


# ── INT8 quantization ─────────────────────────────────────────────────────────


def quantize_int8(fp32_path: Path, int8_path: Path) -> None:
    """Quantize ONNX FP32 model to INT8 via onnxruntime static quantization."""
    from onnxruntime.quantization import QuantType, quantize_dynamic

    logger.info("Quantizing to INT8: %s", int8_path)
    int8_path.parent.mkdir(parents=True, exist_ok=True)

    quantize_dynamic(
        model_input=str(fp32_path),
        model_output=str(int8_path),
        weight_type=QuantType.QInt8,
        optimize_model=True,
    )
    logger.info("INT8 quantization complete: %s", int8_path)

    orig_mb = fp32_path.stat().st_size / 1e6
    quant_mb = int8_path.stat().st_size / 1e6
    logger.info(
        "Size: FP32=%.1fMB  INT8=%.1fMB  (%.0f%% reduction)",
        orig_mb,
        quant_mb,
        (1 - quant_mb / orig_mb) * 100,
    )


# ── Latency validation ────────────────────────────────────────────────────────


def validate_latency(int8_path: Path, tokenizer_dir: Path, n_samples: int = 20) -> None:
    """Assert all inference calls complete in <10ms on CPU."""
    import onnxruntime as ort
    from transformers import AutoTokenizer

    logger.info("Validating INT8 model latency (%d samples)...", n_samples)
    tokenizer = AutoTokenizer.from_pretrained(str(tokenizer_dir))

    opts = ort.SessionOptions()
    opts.intra_op_num_threads = 2
    session = ort.InferenceSession(
        str(int8_path), sess_options=opts, providers=["CPUExecutionProvider"]
    )

    test_texts = [
        "What does the Bible say about faith?",
        "Find me ML Engineer jobs in Dallas",
        "What is NVDA stock price today?",
        "Write a YouTube script about LangGraph",
        "Explain the Sermon on the Mount",
        "Help me rewrite my resume",
        "Show me recent AI research papers",
        "Create a D2 diagram for my architecture",
        "What does Romans 8 mean?",
        "Find data scientist jobs near Plano TX",
    ]

    latencies: list[float] = []
    for i in range(n_samples):
        text = test_texts[i % len(test_texts)]
        inputs = tokenizer(
            text,
            return_tensors="np",
            max_length=_MAX_LENGTH,
            padding="max_length",
            truncation=True,
        )
        feeds = {
            "input_ids": inputs["input_ids"].astype(np.int64),
            "attention_mask": inputs["attention_mask"].astype(np.int64),
        }
        t0 = time.perf_counter()
        logits = session.run(None, feeds)[0][0]
        latencies.append((time.perf_counter() - t0) * 1000)
        pred = _LABEL_NAMES[int(np.argmax(logits))]
        logger.debug("  [%d] %s → %s (%.2fms)", i, text[:40], pred, latencies[-1])

    p50 = sorted(latencies)[len(latencies) // 2]
    p99 = sorted(latencies)[int(len(latencies) * 0.99)]
    logger.info("Latency p50=%.2fms  p99=%.2fms  max=%.2fms", p50, p99, max(latencies))

    slow = [lat for lat in latencies if lat > 10.0]
    if slow:
        logger.warning(
            "%d/%d samples exceeded 10ms threshold (max=%.2fms)",
            len(slow),
            n_samples,
            max(slow),
        )
    else:
        logger.info("All %d samples under 10ms ✓", n_samples)


# ── Accuracy spot-check ───────────────────────────────────────────────────────


def validate_accuracy(int8_path: Path, tokenizer_dir: Path) -> None:
    """Spot-check the INT8 model against hard-coded ground truth examples."""
    import onnxruntime as ort
    from transformers import AutoTokenizer

    logger.info("Spot-checking INT8 model accuracy...")
    tokenizer = AutoTokenizer.from_pretrained(str(tokenizer_dir))

    opts = ort.SessionOptions()
    opts.intra_op_num_threads = 2
    session = ort.InferenceSession(
        str(int8_path), sess_options=opts, providers=["CPUExecutionProvider"]
    )

    checks = [
        ("What does the Bible say about prayer?", "spiritual"),
        ("Find me ML Engineer jobs in Dallas", "career"),
        ("What is NVDA stock price today?", "intelligence"),
        ("Write a YouTube script about LangGraph", "creative"),
        ("Explain John 3:16", "spiritual"),
        ("Help me rewrite my resume for a machine learning role", "career"),
        ("Show me the latest AI research papers", "intelligence"),
        ("Draft a LinkedIn post about my AI project", "creative"),
    ]

    correct = 0
    for text, expected in checks:
        inputs = tokenizer(
            text,
            return_tensors="np",
            max_length=_MAX_LENGTH,
            padding="max_length",
            truncation=True,
        )
        feeds = {
            "input_ids": inputs["input_ids"].astype(np.int64),
            "attention_mask": inputs["attention_mask"].astype(np.int64),
        }
        logits = session.run(None, feeds)[0][0]
        pred = _LABEL_NAMES[int(np.argmax(logits))]
        status = "✓" if pred == expected else "✗"
        logger.info("  %s expected=%s  got=%s  | %s", status, expected, pred, text[:50])
        if pred == expected:
            correct += 1

    accuracy = correct / len(checks)
    logger.info("Spot-check accuracy: %d/%d (%.0f%%)", correct, len(checks), accuracy * 100)
    if accuracy < 0.75:
        logger.warning("Accuracy below 75%% — consider more training data or epochs")


# ── Main ──────────────────────────────────────────────────────────────────────


def main() -> None:
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(levelname)s %(message)s",
        datefmt="%H:%M:%S",
    )

    parser = argparse.ArgumentParser(description="Train DistilBERT router + export ONNX INT8")
    parser.add_argument(
        "--data",
        type=Path,
        default=Path("data/router_train.jsonl"),
        help="Training JSONL (default: data/router_train.jsonl)",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("data/models/router.onnx"),
        help="Output ONNX INT8 path (default: data/models/router.onnx)",
    )
    parser.add_argument("--epochs", type=int, default=3)
    parser.add_argument("--batch-size", type=int, default=16)
    parser.add_argument("--lr", type=float, default=2e-5)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument(
        "--skip-train",
        action="store_true",
        help="Skip training; quantize an existing HF model at data/models/hf_model",
    )
    args = parser.parse_args()

    output_dir = args.output.parent
    fp32_path = output_dir / "router_fp32.onnx"
    hf_model_dir = output_dir / "hf_model"

    if not args.skip_train:
        if not args.data.exists():
            logger.error(
                "Training data not found at %s — run generate-synth-data.py first", args.data
            )
            raise SystemExit(1)

        hf_model_dir = train(
            data_path=args.data,
            output_dir=output_dir,
            epochs=args.epochs,
            batch_size=args.batch_size,
            lr=args.lr,
            seed=args.seed,
        )
    else:
        logger.info("Skipping training (--skip-train), using existing model at %s", hf_model_dir)
        if not hf_model_dir.exists():
            logger.error("No HF model found at %s", hf_model_dir)
            raise SystemExit(1)

    export_onnx(hf_model_dir, fp32_path)
    quantize_int8(fp32_path, args.output)
    validate_latency(args.output, hf_model_dir)
    validate_accuracy(args.output, hf_model_dir)

    logger.info("=" * 60)
    logger.info("Router model ready: %s", args.output)
    logger.info("Set ROUTER_MODEL_PATH=%s in .env to activate ONNX inference", args.output)
    logger.info("=" * 60)


if __name__ == "__main__":
    main()
